apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  test-root-username: YjdiZmM5ZmU0YjZjMWU=
  test-root-password: Y2Y0MTBiZmI=
  test-root-name: aGVyb2t1XzBhYzgxNWIzMDg5YzA5MQ==