apiVersion: v1
kind: Service
metadata:
  name: {{ include "express_mongo.fullname" . }}
  labels:
    {{- include "express_mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "express_mongo.selectorLabels" . | nindent 4 }}
